[package]
name    = "dit-vcs"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
dit-model = { workspace = true }
dit-parse = { workspace = true }
similar    = { workspace = true }
thiserror  = { workspace = true }
time       = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
