// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryCountsDto } from "./CategoryCountsDto";
import type { ChangeSummaryDto } from "./ChangeSummaryDto";
import type { DayCountDto } from "./DayCountDto";

/**
 * The workspace then, the workspace now, and what happened in between —
 * all recomputed from `field_events` on read (invariant 5).
 */
export type ActivitySummaryDto = { 
/**
 * The cutoff this summary was taken at, as a position in the commit
 * graph. Dates map to one only through an author's clock; a `seq` is
 * exact.
 */
seq: number, 
/**
 * The end of recorded history: the `seq` that means "now".
 */
max_seq: number, days: Array<DayCountDto>, at_cutoff: CategoryCountsDto, now: CategoryCountsDto, since: ChangeSummaryDto, };
