// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the workspace activity feed: a field change, plus enough of
 * the issue to render it without a second request per row.
 */
export type ActivityEventDto = { seq: number, issue_id: string, 
/**
 * The issue's permanent handle, for opening it from the feed.
 */
short_ref: string, 
/**
 * `Some(12)` displays as `#12`; absent until the issue is numbered.
 */
number: number | null, 
/**
 * Empty when the issue no longer exists — history outlives its subject.
 */
title: string, field: string, old_value: string | null, new_value: string | null, author: string, ts: string, commit_sha: string, };
