// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityEventDto } from "./ActivityEventDto";

/**
 * A page of the feed. `next_before_seq` is the cursor for the next page,
 * or absent at the end of history.
 */
export type ActivityPageDto = { events: Array<ActivityEventDto>, next_before_seq: number | null, };
