// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an uploaded picture landed (ADR 0026), and the relative link to
 * write into the markdown that shows it.
 */
export type AttachedDto = { path: string, link: string, };
