// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlockerDto = { id: string, short_ref: string, number: number | null, title: string, status: string, 
/**
 * `satisfied` | `unsatisfied` | `broken` (cancelled or gone).
 */
state: string, };
