// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BoardIssueDto = { id: string, short_ref: string, number: number | null, title: string, priority: string | null, 
/**
 * The free-form lane, for the board's lane filter (ADR 0019).
 */
lane: string | null, type: string, assignees: Array<string>, labels: Array<string>, estimate: number | null, updated: string, };
