// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardIssueDto } from "./BoardIssueDto";

/**
 * Flat on purpose: the stray "not in workflow" column has no workflow
 * status behind it, so there is no `StatusDto` to nest — the client that
 * wants categories already fetched `/api/schema`.
 */
export type BoardColumnDto = { id: string, label: string, wip_limit: number | null, issues: Array<BoardIssueDto>, };
