// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderPurpose } from "./FolderPurpose";

export type ChooseFolderDto = { 
/**
 * What the folder is for — it words the dialog's prompt.
 */
purpose?: FolderPurpose, };
