// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The claim request (ADR 0015): `{"action":"claim"}` plus the escape
 * hatches. `action` defaults to `claim`.
 */
export type ClaimRequestDto = { 
/**
 * `claim` | `renew` | `takeover` | `release`.
 */
action: string | null, force: boolean, };
