// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `claim` did — `wrote: false` means no commit was needed.
 */
export type ClaimReportDto = { wrote: boolean, note: string, };
