// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodeNeighbourDto = { path: string, generated: boolean, users: number, names: Array<string>, via: string | null, };
