// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeApiOperationDto } from "./CodeApiOperationDto";

/**
 * One API path a file calls, and the operations it reaches.
 */
export type CodeApiCallDto = { line: number, 
/**
 * With the constants it is built from put back in.
 */
path: string, 
/**
 * Empty for an orphan: no registered spec describes it.
 */
operations: Array<CodeApiOperationDto>, };
