// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeRootDto } from "./CodeRootDto";

/**
 * The roots, after a refresh to HEAD.
 */
export type CodeRootsDto = { roots: Array<CodeRootDto>, 
/**
 * Files parsed by the refresh this answer ran.
 */
parsed: number, 
/**
 * Roots that could not be read, with why.
 */
problems: Array<string>, };
