// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file of the whole-root network.
 */
export type CodeGraphFileDto = { path: string, generated: boolean, 
/**
 * Files importing it.
 */
users: number, };
