// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeGraphFileDto } from "./CodeGraphFileDto";

/**
 * Every file of a root and every import between them. Edges are pairs of
 * indexes into `files`, importer first — the whole network is thousands of
 * edges, and paths repeated in each would multiply the payload.
 */
export type CodeGraphDto = { root: string, files: Array<CodeGraphFileDto>, edges: Array<[number, number]>, };
