// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A code root the map screen can open.
 */
export type CodeRootDto = { id: string, 
/**
 * The linked repository it reads, or `None` for this one.
 */
repo: string | null, 
/**
 * The pinned branch or tag, when there is one.
 */
git_ref: string | null, files: number, };
