// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeApiCallDto } from "./CodeApiCallDto";
import type { CodeNeighbourDto } from "./CodeNeighbourDto";

/**
 * One file in focus, with both of its sides.
 */
export type CodeNeighbourhoodDto = { root: string, path: string, generated: boolean, defines: Array<string>, users: Array<CodeNeighbourDto>, uses: Array<CodeNeighbourDto>, external: Array<string>, api_calls: Array<CodeApiCallDto>, };
