// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodeApiOperationDto = { spec: string, operation_id: string, method: string, path: string, 
/**
 * Environments where a scenario exercising it holds a fresh proof.
 */
proven: Array<string>, };
