// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeUnitDto } from "./CodeUnitDto";
import type { CodeUnitEdgeDto } from "./CodeUnitEdgeDto";

/**
 * One folder of a root, drawn.
 */
export type CodeOverviewDto = { root: string, folder: string, units: Array<CodeUnitDto>, edges: Array<CodeUnitEdgeDto>, };
