// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommentDto = { id: string, issue_id: string, author: string, created: string, 
/**
 * The parent comment this replies to (§4.4); absent = top-level.
 */
reply_to: string | null, body: string, body_html: string, };
