// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommentDto = { id: string, issue_id: string, author: string, created: string, body: string, body_html: string, };
