// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommentInputDto = { body: string, 
/**
 * The parent comment this replies to (§4.4): its id or 7-char short
 * form, resolved among this issue's comments. Absent = top-level.
 */
reply_to?: string, };
