// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DayCountDto = { 
/**
 * `YYYY-MM-DD`, UTC.
 */
day: string, count: number, };
