// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A page's contents, addressed by its `docs/…` path. Saves return the
 * formatted body that landed, so the editor can show the canonical form.
 */
export type DocBodyDto = { path: string, body: string, };
