// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the Docs listing (ADR 0010). `updated_ms` is the file's
 * mtime, display metadata only — the page's real history is git.
 */
export type DocEntryDto = { path: string, updated_ms: number, bytes: number, };
