// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A kind of document a page can be made from (ADR 0031).
 */
export type DocTemplateDto = { id: string, name: string, 
/**
 * What the document answers, in a sentence.
 */
summary: string, 
/**
 * Where a page of this kind is placed, e.g. `docs/business`.
 */
folder: string, built_in: boolean, 
/**
 * The workspace's own `docs/.templates/<id>.md` replaces the built-in.
 */
overridden: boolean, };
