// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldPatchDto = { title?: string, type?: string, status?: string, priority?: string, assignees?: Array<string>, labels?: Array<string>, reporter?: string, estimate?: number, sprint?: string, due?: string, };
