// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldEventDto = { seq: number, field: string, old_value: string | null, new_value: string | null, author: string, ts: string, commit_sha: string, };
