// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One issue patch. Three states per optional field: key absent — untouched;
 * `null` (or `""` for strings) — cleared, the key leaves the file; a value —
 * set. Required fields (`title`, `type`, `status`) only take values, and the
 * list fields clear by being set to `[]`.
 */
export type FieldPatchDto = { title?: string, type?: string, status?: string, 
/**
 * `p0`..`p4`; `null` or `""` clears.
 */
priority?: string | null, assignees?: Array<string>, labels?: Array<string>, reporter?: string, 
/**
 * The full 26-character id of the parent epic; `null` or `""` clears.
 */
epic?: string | null, 
/**
 * `null` clears.
 */
estimate?: number | null, 
/**
 * `null` or `""` clears.
 */
sprint?: string | null, 
/**
 * `YYYY-MM-DD`; `null` or `""` clears.
 */
due?: string | null, 
/**
 * `YYYY-MM-DD`; `null` or `""` clears.
 */
start?: string | null, 
/**
 * Replaces the whole list, like `assignees` and `labels`. Each entry is
 * a full 26-character issue id.
 */
blocked_by?: Array<string>, 
/**
 * The non-gating relation (ADR 0020). Replaces the whole list.
 */
fed_by?: Array<string>, 
/**
 * The lane id (ADR 0015); `null` or `""` clears back to Unlaned.
 */
lane?: string | null, 
/**
 * Replaces the whole membership set, like `labels` (ADR 0019).
 */
flows?: Array<string>, };
