// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowEdgeDto } from "./FlowEdgeDto";
import type { FlowGroupDto } from "./FlowGroupDto";
import type { FlowLaneDto } from "./FlowLaneDto";
import type { FlowNodeDto } from "./FlowNodeDto";
import type { FlowPhaseDto } from "./FlowPhaseDto";
import type { FlowShapeProblemDto } from "./FlowShapeProblemDto";

/**
 * One flow rendered as a diagram: nodes on a computed stage grid, edges
 * from `blocked_by`, the critical path highlighted.
 */
export type FlowBoardDto = { 
/**
 * Absent for the union of every flow.
 */
name: string | null, lanes: Array<FlowLaneDto>, 
/**
 * The authored columns (ADR 0020); empty when this flow has no fence.
 */
phases: Array<FlowPhaseDto>, groups: Array<FlowGroupDto>, 
/**
 * A trailing "Unphased" column is drawn.
 */
unphased: boolean, 
/**
 * Why the fence could not be used, when there is one and it could not.
 */
shape_problem: FlowShapeProblemDto | null, stages: number, nodes: Array<FlowNodeDto>, edges: Array<FlowEdgeDto>, 
/**
 * The critical path, root first, as issue ids.
 */
main_path: Array<string>, };
