// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlowOutsideBlockerDto = { id: string, short_ref: string, number: number | null, title: string, status_label: string, 
/**
 * Through the gate already — it no longer holds the node.
 */
satisfied: boolean, 
/**
 * Not in the index at all: a dangling reference.
 */
gone: boolean, };
