// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The flow diagram (ADR 0019): every flow with its member count.
 */
export type FlowSummaryDto = { name: string, issues: number, };
