// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlowGroupDto = { id: string, label: string, 
/**
 * `null` is the unlaned band.
 */
lane: string | null, 
/**
 * Phase ids the frame covers.
 */
phases: Array<string>, };
