// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowClaimDto } from "./FlowClaimDto";
import type { FlowOutsideBlockerDto } from "./FlowOutsideBlockerDto";

export type FlowNodeDto = { id: string, short_ref: string, number: number | null, title: string, 
/**
 * `task` | `bug` | `story` | `spike` | `chore`.
 */
kind: string, status: string, status_label: string, category: string | null, priority: string | null, lane: string | null, 
/**
 * The computed column.
 */
stage: number, 
/**
 * Draw order within the (lane, stage) cell.
 */
row: number, 
/**
 * Every phase this issue's labels claim; more than one is legal and is
 * shown rather than hidden.
 */
phases: Array<string>, 
/**
 * `ready` | `not_pickable` | `blocked`.
 */
readiness: string, 
/**
 * Blockers that are not members of this board: they gate the node but
 * cannot be drawn, so they travel with it by name.
 */
outside_blockers: Array<FlowOutsideBlockerDto>, claim: FlowClaimDto | null, 
/**
 * Commits that have touched this issue — derived, never authored.
 */
commits: number, };
