// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowClaimDto } from "./FlowClaimDto";

export type FlowNodeDto = { id: string, short_ref: string, number: number | null, title: string, status: string, status_label: string, category: string | null, priority: string | null, lane: string | null, 
/**
 * The computed column.
 */
stage: number, 
/**
 * Draw order within the (lane, stage) cell.
 */
row: number, 
/**
 * `ready` | `not_pickable` | `blocked`.
 */
readiness: string, 
/**
 * Blockers outside this board, summarized as a count.
 */
outside_blockers: number, claim: FlowClaimDto | null, };
