// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowEdgeDto } from "./FlowEdgeDto";
import type { FlowLaneDto } from "./FlowLaneDto";
import type { FlowNodeDto } from "./FlowNodeDto";

/**
 * One flow rendered as a diagram: nodes on a computed stage grid, edges
 * from `blocked_by`, the critical path highlighted.
 */
export type FlowBoardDto = { 
/**
 * Absent for the union of every flow.
 */
name: string | null, lanes: Array<FlowLaneDto>, stages: number, nodes: Array<FlowNodeDto>, edges: Array<FlowEdgeDto>, 
/**
 * The critical path, root first, as issue ids.
 */
main_path: Array<string>, };
