// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FolderChosenDto = { 
/**
 * `null` when the person cancelled.
 */
path: string | null, 
/**
 * The chosen folder already is a DIT workspace — "New workspace" must
 * not make another inside it; the page offers to add it instead.
 */
is_workspace: boolean, };
