// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FolderChosenDto = { 
/**
 * `null` when the person cancelled.
 */
path: string | null, };
