// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IssueDto = { id: string, short_ref: string, 
/**
 * The human-friendly handle (ADR 0007): `Some(12)` displays as `#12`.
 * Absent until assigned — never invented client-side.
 */
number: number | null, title: string, type: string, status: string, priority: string | null, reporter: string | null, assignees: Array<string>, labels: Array<string>, epic: string | null, estimate: number | null, sprint: string | null, due: string | null, 
/**
 * When the work is planned to begin, `YYYY-MM-DD`. Absent for most
 * issues — the plan views infer a bar from `due` and the estimate
 * rather than writing one back.
 */
start: string | null, 
/**
 * Ids of the issues this one waits on, in the file's order. Empty when
 * nothing blocks it — always present so the client never has to guess.
 */
blocked_by: Array<string>, created: string, updated: string, body: string, body_html: string, };
