// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueDto } from "./IssueDto";

export type IssueListDto = { total: number, items: Array<IssueDto>, };
