// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MorseCheckDto = { 
/**
 * A JSONPath into the response body.
 */
path: string, 
/**
 * `exists` | `equals`.
 */
rule: string, 
/**
 * What `equals` compares with — a literal or a `{{name}}`.
 */
value: string, };
