// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One change to a scenario from the screen (ADR 0027).
 */
export type MorseScenarioEditDto = { "op": "rename", to: string, } | { "op": "set_env", env: string | null, } | { "op": "set_requires", names: Array<string>, } | { "op": "delete_step", step: string, } | { "op": "move_step", step: string, to: number, } | { "op": "duplicate_step", step: string, as_id: string, } | { "op": "rename_step", step: string, to: string, };
