// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorsePairDto } from "./MorsePairDto";
import type { MorsePartDto } from "./MorsePartDto";

/**
 * A step's body in one of its four shapes (ADR 0027). `json` carries the
 * JSON as text, the way the Body tab edits it.
 */
export type MorseBodyDto = { "kind": "json", text: string, } | { "kind": "form", fields: Array<MorsePairDto>, } | { "kind": "raw", media_type: string, text: string | null, file: string | null, } | { "kind": "multipart", parts: Array<MorsePartDto>, };
