// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One step of a run, as a screen shows it. No response body and no captured
 * value: a response is the likeliest place in the product for a real token
 * to appear, so what crosses this boundary is that a capture happened, not
 * what it was (§20.7).
 */
export type MorseRunStepDto = { id: string, method: string, status: number | null, duration_ms: number, passed: boolean, detail: string, };
