// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseInlineRequestDto } from "./MorseInlineRequestDto";
import type { MorseStepDto } from "./MorseStepDto";

export type MorseScenarioDetailDto = { scenario: string, path: string, line: number, spec_id: string, pin: string, env: string | null, requires: Array<string>, requests: Array<MorseInlineRequestDto>, steps: Array<MorseStepDto>, 
/**
 * The fence as the document holds it — what the Fence panel shows.
 */
fence: string, 
/**
 * False when the fence has a `#` comment, which a form would drop.
 */
editable: boolean, };
