// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MorseCaptureDto = { name: string, 
/**
 * `$.path`, `header:Name` or `status`.
 */
from: string, };
