// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseInlineRequestDto } from "./MorseInlineRequestDto";
import type { MorseStepDto } from "./MorseStepDto";

/**
 * What "Save to scenario" posts for a scenario that does not exist yet.
 */
export type MorseCreateDto = { 
/**
 * The document the fence is appended to, created if absent.
 */
doc: string, name: string, spec_id: string, env: string | null, step: MorseStepDto, 
/**
 * Requests the first step calls that no spec describes (ADR 0027).
 */
requests?: Array<MorseInlineRequestDto>, };
