// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseScenarioDto } from "./MorseScenarioDto";
import type { MorseSpecDto } from "./MorseSpecDto";

export type MorseReportDto = { specs: Array<MorseSpecDto>, scenarios: Array<MorseScenarioDto>, 
/**
 * Nothing broken or unreadable. Stale does not make it dirty.
 */
clean: boolean, };
