// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One variable: a value to set, or `null` to remove it.
 */
export type MorseEnvVarSetDto = { name: string, value: string | null, };
