// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseEnvVarSetDto } from "./MorseEnvVarSetDto";

/**
 * Set an environment's server and values from the page (ADR 0027). Values
 * travel one way: the answer to this is `MorseEnvsDto`, which holds names.
 */
export type MorseEnvSetDto = { 
/**
 * Absent keeps the server; `null` clears it.
 */
server?: string | null, vars: Array<MorseEnvVarSetDto>, };
