// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseEnvDto } from "./MorseEnvDto";

export type MorseEnvsDto = { envs: Array<MorseEnvDto>, allow_hosts: Array<string>, };
