// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MorseImportStepDto = { id: string, method: string, 
/**
 * `<spec>/<operationId>`, or `request <path>` for one no spec describes.
 */
target: string, };
