// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseBodyDto } from "./MorseBodyDto";
import type { MorseCaptureDto } from "./MorseCaptureDto";
import type { MorseCheckDto } from "./MorseCheckDto";
import type { MorseInlineRequestDto } from "./MorseInlineRequestDto";
import type { MorsePairDto } from "./MorsePairDto";

/**
 * A step to save, and — when it calls a request the page typed — that
 * request, so both land in one commit (ADR 0027).
 */
export type MorseSaveStepDto = { define_request?: MorseInlineRequestDto, id: string, 
/**
 * `<spec>/<operationId>`, or absent when the step calls `request`.
 */
operation: string | null, 
/**
 * An inline request declared in the fence's `requests:`.
 */
request: string | null, params: Array<MorsePairDto>, query: Array<MorsePairDto>, headers: Array<MorsePairDto>, 
/**
 * Absent for no body.
 */
body: MorseBodyDto | null, status: number | null, checks: Array<MorseCheckDto>, capture: Array<MorseCaptureDto>, };
