// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseImportStepDto } from "./MorseImportStepDto";

export type MorseImportScenarioDto = { name: string, spec: string, requires: Array<string>, steps: Array<MorseImportStepDto>, };
