// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to import (ADR 0027): a `curl` command or a Postman collection.
 */
export type MorseImportDto = { 
/**
 * `curl` or `postman`.
 */
kind: string, text: string, 
/**
 * The scenario a curl import is called.
 */
scenario?: string, 
/**
 * The spec a `{{baseUrl}}` host, or a host nothing names, stands for.
 */
spec?: string, 
/**
 * Where the fences go; required to import, ignored by a preview.
 */
doc?: string, };
