// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseOperationDto } from "./MorseOperationDto";

export type MorseSpecDto = { id: string, 
/**
 * The linked repo holding it (Mode A), absent for this workspace.
 */
repo: string | null, path: string, title: string | null, version: string | null, head: string | null, operations: Array<MorseOperationDto>, 
/**
 * Why the document could not be read. A spec with a problem is still
 * listed: a service whose document went missing is worth saying.
 */
problem: string | null, };
