// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `multipart/form-data` part: a value or a repository file.
 */
export type MorsePartDto = { name: string, value: string | null, file: string | null, media_type: string | null, };
