// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseImportScenarioDto } from "./MorseImportScenarioDto";

/**
 * What an import would write — or, after an import, what it wrote.
 */
export type MorseImportPreviewDto = { scenarios: Array<MorseImportScenarioDto>, notes: Array<string>, };
