// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseSendRequestDto } from "./MorseSendRequestDto";
import type { MorseStepDto } from "./MorseStepDto";

/**
 * What the Send control posts.
 */
export type MorseSendDto = { env: string | null, step: MorseStepDto, 
/**
 * What an inline step calls (ADR 0027): the spec whose server it goes
 * to, and the method and path the page typed. Never a host.
 */
request?: MorseSendRequestDto, };
