// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseStepDto } from "./MorseStepDto";

/**
 * What the Send control posts.
 */
export type MorseSendDto = { env: string | null, step: MorseStepDto, };
