// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MorseScenarioDto = { scenario: string, path: string, line: number, spec_id: string, pin: string, env: string | null, steps: Array<string>, 
/**
 * Variable *names* the environment must provide — never values.
 */
requires: Array<string>, 
/**
 * `fresh` | `stale` | `broken` | `unreadable`.
 */
health: string, 
/**
 * Commits the spec has moved since the pin, when stale.
 */
stale_by: number | null, 
/**
 * Why it cannot be run as written, or why the fence did not parse.
 */
reasons: Array<string>, };
