// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseRunStepDto } from "./MorseRunStepDto";

export type MorseRunDto = { scenario: string, 
/**
 * Seconds since the epoch.
 */
ran_at: number, passed: boolean, 
/**
 * Set when this machine does not allow the host, carrying the command
 * that would change that. The browser never changes it itself.
 */
refused: string | null, steps: Array<MorseRunStepDto>, };
