// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Register an OpenAPI document as a spec (ADR 0027).
 */
export type MorseRegisterSpecDto = { id: string, path: string, 
/**
 * A `repos:` entry holding the file (Mode A); absent for this repo.
 */
repo?: string, };
