// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseCaptureDto } from "./MorseCaptureDto";
import type { MorseCheckDto } from "./MorseCheckDto";
import type { MorsePairDto } from "./MorsePairDto";

export type MorseStepDto = { id: string, 
/**
 * `<spec>/<operationId>`, or absent when the step calls `request`.
 */
operation: string | null, 
/**
 * An inline request declared in the fence's `requests:`.
 */
request: string | null, params: Array<MorsePairDto>, query: Array<MorsePairDto>, headers: Array<MorsePairDto>, 
/**
 * JSON text, or absent for no body.
 */
body: string | null, status: number | null, checks: Array<MorseCheckDto>, capture: Array<MorseCaptureDto>, };
