// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorseFieldDto } from "./MorseFieldDto";
import type { MorseParamDto } from "./MorseParamDto";

/**
 * Morse (§20, ADR 0022). A read-only view: the catalogue derived from each
 * registered OpenAPI document, and every scenario judged against it. No
 * endpoint here sends a request — Morse 1 has no egress at all (I11).
 */
export type MorseOperationDto = { operation_id: string, method: string, path: string, summary: string | null, 
/**
 * The operation's first OpenAPI tag — how the explorer groups it.
 */
tag: string | null, params: Array<MorseParamDto>, 
/**
 * Top-level JSON body fields, to pre-fill a draft from.
 */
body: Array<MorseFieldDto>, responses: Array<string>, };
