// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A page move: `from` and `to` are workspace-relative doc paths.
 */
export type MoveDocDto = { from: string, to: string, };
