// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Make a page from a document template.
 */
export type NewDocFromTemplateDto = { kind: string, title: string, };
