// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The create request. Everything but the title is optional; the server
 * stamps reporter and timestamps.
 */
export type NewIssueDto = { title: string, type?: string, status?: string, priority?: string, assignees?: Array<string>, labels?: Array<string>, estimate?: number, body: string, };
