// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewWorkspaceDto = { name: string, 
/**
 * The folder to make it in, instead of the default root. Must exist.
 */
at?: string, };
