// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A release plan (DESIGN.md §15.2, ADR 0014) as the roadmap reads it. Every
 * field is what the file says — `includes` is the release's *claim*, not a
 * verified fact; nothing here has asked git.
 */
export type ReleaseDto = { version: string, 
/**
 * `planned | in_dev | in_uat | released | rolled_back`.
 */
status: string, target_ref: string | null, repo: string | null, 
/**
 * The planned date, `YYYY-MM-DD` — where the roadmap draws the milestone.
 */
target: string | null, 
/**
 * Full ids of the issues the plan claims, in the file's order.
 */
includes: Array<string>, 
/**
 * Repo-relative path of the plan file, for opening it.
 */
path: string, };
