// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The release patch: `{ status?, target? }`. Absent fields are untouched.
 * Only these two are editable here — the scope (`includes`) is filled by
 * `dit release plan` (v0.9), and the version is the file's identity.
 */
export type ReleasePatchDto = { status?: string, target?: string, };
