// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldPatchDto } from "./FieldPatchDto";

/**
 * The patch request: `{ "set": { ...fields } }`. Absent fields are
 * untouched; there is no way to clear a field in v0.1 — that is a
 * deliberate limit of the write surface, not an oversight.
 */
export type SetIssueDto = { set: FieldPatchDto, };
