// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldPatchDto } from "./FieldPatchDto";

/**
 * The patch request: `{ "set": { ...fields } }`. Absent fields are
 * untouched. The optional fields (`priority`, `epic`, `estimate`, `sprint`,
 * `due`, `start`) can also be cleared: send `null`, or `""` for the string
 * ones, and the key is removed from the file.
 */
export type SetIssueDto = { set: FieldPatchDto, };
