// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The change request. Absent fields are untouched — the same contract as
 * the issue patch.
 */
export type SetSettingsDto = { layout?: string, numbering?: string, 
/**
 * The alias later writes are attributed to. Saved in the clone's git
 * config (never committed); lowercase letters, digits and dashes.
 */
me?: string, };
