// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The workspace's user-facing configuration (ADRs 0005 + 0007) — the thing
 * `dit ui` shows so the layout is never a surprise and never a CLI-only
 * knob. Both fields are closed enums on the wire; there is no free-form
 * path to mistype into.
 */
export type SettingsDto = { 
/**
 * `root` or `dotdir` — where issue content lives.
 */
layout: string, 
/**
 * `local` or `on-merge` — when an issue gets its `number:`.
 */
numbering: string, 
/**
 * Template names creation can seed a body from.
 */
templates: Array<string>, };
