// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatusInfo = { ok: boolean, version: string, repo: string, branch: string, head: string | null, dirty: boolean, 
/**
 * The alias writes are attributed to, if the server knows one.
 */
me: string | null, };
