// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatusDto = { id: string, label: string, category: string, terminal: boolean, wip_limit: number | null, };
