// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowCardDto } from "./WorkflowCardDto";

export type WorkflowLaneDto = { 
/**
 * Absent for the Unlaned row.
 */
id: string | null, label: string, owners: Array<string>, cards: Array<WorkflowCardDto>, };
