// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockerDto } from "./BlockerDto";
import type { ClaimDto } from "./ClaimDto";

export type WorkflowCardDto = { id: string, short_ref: string, number: number | null, title: string, status: string, status_label: string, category: string | null, priority: string | null, 
/**
 * `ready` | `not_pickable` | `blocked`.
 */
readiness: string, 
/**
 * The blockers keeping a card back, each with where it stands.
 */
blockers: Array<BlockerDto>, claim: ClaimDto | null, };
