// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinationDto } from "./CoordinationDto";
import type { DerivedDto } from "./DerivedDto";
import type { LaneDto } from "./LaneDto";
import type { StatusDto } from "./StatusDto";
import type { TransitionDto } from "./TransitionDto";

export type WorkflowDto = { statuses: Array<StatusDto>, transitions: Array<TransitionDto>, derived: Array<DerivedDto>, 
/**
 * The lane registry (ADR 0015); empty when the workspace declares none.
 */
lanes: Array<LaneDto>, 
/**
 * The coordination knobs (ADR 0015) the UI needs to render claim age.
 */
coordination: CoordinationDto, };
