// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the workspace comment feed: a comment plus enough of its
 * issue to render it without a second request per row.
 */
export type WorkspaceCommentDto = { id: string, issue_id: string, 
/**
 * The issue's permanent handle, for opening it from the feed.
 */
short_ref: string, 
/**
 * `Some(12)` displays as `#12`; absent until the issue is numbered.
 */
number: number | null, 
/**
 * Empty when the issue is no longer indexed.
 */
title: string, author: string, created: string, body: string, body_html: string, };
