// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DerivedDto } from "./DerivedDto";
import type { StatusDto } from "./StatusDto";
import type { TransitionDto } from "./TransitionDto";

export type WorkflowDto = { statuses: Array<StatusDto>, transitions: Array<TransitionDto>, derived: Array<DerivedDto>, };
