// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceDto } from "./WorkspaceDto";

export type WorkspacesDto = { workspaces: Array<WorkspaceDto>, default: string | null, 
/**
 * Where "New workspace" puts one.
 */
root: string, };
