// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowLaneDto } from "./WorkflowLaneDto";

/**
 * The coordination board (ADR 0015): one row per lane, Unlaned last, every
 * card carrying its derived readiness, blocker states and claim liveness.
 * Read-only — writes go through the issue and claim endpoints.
 */
export type WorkflowBoardDto = { lanes: Array<WorkflowLaneDto>, claim_ttl_minutes: number, };
