// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceDto } from "./WorkspaceDto";

export type WorkspacesDto = { workspaces: Array<WorkspaceDto>, default: string | null, 
/**
 * Where "New workspace" puts one unless a folder is chosen.
 */
root: string, 
/**
 * Whether "Choose folder…" can open the system's dialog (ADR 0030).
 */
can_choose_folder: boolean, };
