//! Where data lives inside the working tree (ADR 0005).
//!
//! The layout is **one boolean, not a path**: content roots sit at the tree
//! root (`root`, the Modes A & B default) or under `.dit/` (`dotdir`, the
//! Mode C default and the pre-ADR-0005 shape). Every consumer — store, indexer,
//! history walker, merge driver — branches on this one bit or it branches on a
//! thousand configs.
//!
//! Everything here is pure string classification over `/`-separated
//! repo-relative paths, so `dit-vcs` and `dit-core` can classify git tree
//! entries without touching the filesystem and without depending on an
//! adapter.

use serde::{Deserialize, Serialize};

/// The five reserved content-root names (ADR 0005). `dit init` refuses to lay
/// out into a tree where one of these already exists and is not DIT-shaped.
pub const CONTENT_ROOTS: [&str; 5] = ["issues", "epics", "docs", "notes", "changelogs"];

/// The issue body file inside an aggregate folder (ADR 0006). A forge renders
/// it automatically, so browsing the repo needs zero tooling.
pub const ISSUE_BODY_FILE: &str = "README.md";

/// The pre-ADR-0006 body file name. Still read, never written for new issues;
/// `dit migrate-layout` renames the stragglers.
pub const LEGACY_ISSUE_BODY_FILE: &str = "issue.md";

/// First line of a generated index README (ADR 0008). The version follows, so
/// consumers match on the prefix. An output, never an input: the indexer skips
/// any file carrying this marker.
pub const GENERATED_INDEX_MARKER: &str = "<!-- generated by dit";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum DataLayout {
    /// Content roots at the tree root; machinery in `.dit/` (Modes A & B).
    #[default]
    #[serde(rename = "root")]
    Root,
    /// Everything under `.dit/` (Mode C, and the pre-ADR-0005 shape).
    #[serde(rename = "dotdir")]
    DotDir,
}

impl DataLayout {
    pub fn as_str(self) -> &'static str {
        match self {
            DataLayout::Root => "root",
            DataLayout::DotDir => "dotdir",
        }
    }

    /// Parse the `config.yaml` wire form. Two closed values — a free-form path
    /// here would be a config surface every consumer has to branch on.
    pub fn parse(s: &str) -> Option<DataLayout> {
        match s {
            "root" => Some(DataLayout::Root),
            "dotdir" => Some(DataLayout::DotDir),
            _ => None,
        }
    }

    /// The repo-relative prefix every content root carries under this layout.
    /// `""` for `root`, `".dit/"` for `dotdir`.
    pub fn content_prefix(self) -> &'static str {
        match self {
            DataLayout::Root => "",
            DataLayout::DotDir => ".dit/",
        }
    }

    /// Repo-relative path of a content root, e.g. `issues` or `.dit/issues`.
    pub fn content_root(self, name: &str) -> String {
        format!("{}{}", self.content_prefix(), name)
    }

    /// Pathspecs limiting a git diff to files DIT owns. Root layout must name
    /// the visible roots too, or field events from issue edits vanish.
    pub fn diff_pathspecs(self) -> &'static [&'static str] {
        match self {
            DataLayout::Root => &["issues/", ".dit/"],
            DataLayout::DotDir => &[".dit/"],
        }
    }
}

/// `issues/2026/08/<folder>/README.md` (or the legacy `issue.md`) — and nothing
/// else. Shape, not filename: `docs/…/README.md` is a doc page, and
/// `issues/README.md` is the generated index (ADR 0008), never an issue body.
pub fn is_issue_body(rel: &str, layout: DataLayout) -> bool {
    let Some(rest) = strip_content_prefix(rel, layout) else {
        return false;
    };
    // issues / year / month / folder / body file
    let segments: Vec<&str> = rest.split('/').collect();
    if segments.len() != 5 || segments[0] != "issues" {
        return false;
    }
    let file = segments[4];
    month_shaped(segments[1], segments[2])
        && !segments[3].is_empty()
        && (file == ISSUE_BODY_FILE || file == LEGACY_ISSUE_BODY_FILE)
}

/// Looser than [`is_issue_body`]: any body-named file anywhere under the
/// issues root, whatever the intermediate folders. The history walker follows
/// a file to wherever it moved (`dit archive`, future refactors) — shape
/// rules would silently amputate history at the move. The generated index is
/// still excluded, and contributes nothing anyway (no `id` frontmatter).
pub fn looks_like_issue_body(rel: &str, layout: DataLayout) -> bool {
    if let Some(rest) = strip_content_prefix(rel, layout) {
        if rest.starts_with("issues/") && !is_generated_index(rel, layout) {
            let file = rest.rsplit('/').next().unwrap_or("");
            if file == ISSUE_BODY_FILE || file == LEGACY_ISSUE_BODY_FILE {
                return true;
            }
        }
    }
    // Root-layout workspaces also accept the pre-ADR-0005 shape under
    // `.dit/issues/`: after a layout migration the FILES live at `issues/…`
    // but the COMMITS that wrote them still name the old path, and the
    // walker must read them or the migration amputates history. Read
    // tolerance only — new writes never go there — and one-directional: a
    // dotdir workspace still refuses unprefixed root-layout paths.
    if layout == DataLayout::Root {
        if let Some(rest) = rel.strip_prefix(".dit/") {
            if rest.starts_with("issues/") && !is_generated_index(rel, DataLayout::DotDir) {
                let file = rest.rsplit('/').next().unwrap_or("");
                if file == ISSUE_BODY_FILE || file == LEGACY_ISSUE_BODY_FILE {
                    return true;
                }
            }
        }
    }
    false
}

/// `<issue folder>/comments/<file>` — the per-comment files the merge driver
/// owns (`**/comments/*.md merge=dit-md`).
pub fn is_comment(rel: &str, layout: DataLayout) -> bool {
    let Some(rest) = strip_content_prefix(rel, layout) else {
        return false;
    };
    let segments: Vec<&str> = rest.split('/').collect();
    // issues / year / month / folder / comments / file
    segments.len() == 6
        && segments[0] == "issues"
        && month_shaped(segments[1], segments[2])
        && !segments[2].is_empty()
        && segments[4] == "comments"
        && segments[5].ends_with(".md")
}

/// The generated index paths under this layout (ADR 0008). Exactly these
/// files are skipped as inputs and written only by the generation command.
pub fn generated_index_paths(layout: DataLayout) -> Vec<String> {
    vec![layout.content_root("issues") + "/README.md"]
}

/// True for exactly the generated-index files — the indexer's skip list.
pub fn is_generated_index(rel: &str, layout: DataLayout) -> bool {
    generated_index_paths(layout)
        .iter()
        .any(|p| rel.trim_end_matches('/') == p.as_str())
}

fn strip_content_prefix(rel: &str, layout: DataLayout) -> Option<&str> {
    rel.strip_prefix(layout.content_prefix())
}

fn month_shaped(year: &str, month: &str) -> bool {
    year.len() == 4
        && year.bytes().all(|b| b.is_ascii_digit())
        && month.len() == 2
        && month.bytes().all(|b| b.is_ascii_digit())
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    #[test]
    fn root_layout_classifies_the_issue_body() {
        assert!(is_issue_body(
            "issues/2026/08/01K3M9ZXQ2-R7VN-fix-login/README.md",
            DataLayout::Root
        ));
    }

    #[test]
    fn dotdir_layout_matches_the_same_paths_under_dot() {
        assert!(is_issue_body(
            ".dit/issues/2026/08/01K3M9ZXQ2-R7VN-fix-login/README.md",
            DataLayout::DotDir
        ));
        // The layouts do not cross-match: a root-layout classifier must not
        // swallow dotdir paths and vice versa.
        assert!(!is_issue_body(
            ".dit/issues/2026/08/01K3M9ZXQ2-R7VN-fix-login/README.md",
            DataLayout::Root
        ));
    }

    #[test]
    fn the_legacy_issue_md_body_still_classifies() {
        assert!(is_issue_body(
            "issues/2026/08/01K3M9ZXQ2-R7VN-fix-login/issue.md",
            DataLayout::Root
        ));
    }

    #[test]
    fn the_generated_index_is_not_an_issue_body() {
        assert!(!is_issue_body("issues/README.md", DataLayout::Root));
        assert!(is_generated_index("issues/README.md", DataLayout::Root));
        assert!(is_generated_index(
            ".dit/issues/README.md",
            DataLayout::DotDir
        ));
        assert!(!is_generated_index(
            "issues/2026/README.md",
            DataLayout::Root
        ));
    }

    #[test]
    fn doc_and_note_readmes_are_not_issue_bodies() {
        assert!(!is_issue_body(
            "docs/ARCHITECTURES/README.md",
            DataLayout::Root
        ));
        assert!(!is_issue_body("notes/2026-08-17.md", DataLayout::Root));
        assert!(!is_issue_body("changelogs/README.md", DataLayout::Root));
    }

    #[test]
    fn comments_classify_by_folder_shape() {
        assert!(is_comment(
            "issues/2026/08/01K3M9ZXQ2-R7VN-fix-login/comments/01M08FFCAX-farid.md",
            DataLayout::Root
        ));
        assert!(!is_comment(
            "issues/2026/08/01K3M9ZXQ2-R7VN-fix-login/README.md",
            DataLayout::Root
        ));
    }

    #[test]
    fn a_body_directly_under_issues_is_rejected_by_shape() {
        assert!(!is_issue_body("issues/2026/README.md", DataLayout::Root));
        assert!(!is_issue_body("issues/README/README.md", DataLayout::Root));
    }

    #[test]
    fn diff_pathspecs_cover_the_visible_roots() {
        assert_eq!(DataLayout::Root.diff_pathspecs(), &["issues/", ".dit/"]);
        assert_eq!(DataLayout::DotDir.diff_pathspecs(), &[".dit/"]);
    }

    #[test]
    fn layout_parses_only_its_two_values() {
        assert_eq!(DataLayout::parse("root"), Some(DataLayout::Root));
        assert_eq!(DataLayout::parse("dotdir"), Some(DataLayout::DotDir));
        // A free-form path is refused, not interpreted.
        assert_eq!(DataLayout::parse("/home/me/data"), None);
    }

    #[test]
    fn the_loose_classifier_follows_pre_migration_history_under_dot() {
        // ADR 0005 migration continuity: after `dit migrate-layout root`, the
        // files live at `issues/…` but the COMMITS that created them still
        // name `.dit/issues/…`. The history walker must follow a file to
        // where it used to live, or the migration amputates history at the
        // move. Read tolerance only — nothing new is ever written there.
        assert!(looks_like_issue_body(
            ".dit/issues/2026/08/one/issue.md",
            DataLayout::Root
        ));
        // The dotdir shape's own generated index stays excluded.
        assert!(!looks_like_issue_body(
            ".dit/issues/README.md",
            DataLayout::Root
        ));
        // And the tolerance is one-directional: a dotdir workspace still
        // refuses unprefixed root-layout paths.
        assert!(!looks_like_issue_body(
            "issues/2026/08/one/README.md",
            DataLayout::DotDir
        ));
    }
}
