[package]
name    = "dit-cli"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
dit-core = { workspace = true }
dit-server = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[[bin]]
name = "dit"
path = "src/main.rs"
