//! The code map's extractor (ADR 0025): one source file in, the facts the
//! index stores out — the symbols it defines, what it imports and from where,
//! what it re-exports, what it calls, and what its types extend.
//!
//! Pure over its input: the caller reads the file through `dit-vcs` (I3) and
//! hands the text here; nothing in this crate touches the disk or the network.

mod kotlin;
mod resolve;
mod rust;
mod ts;

use dit_model::{CodeLang, FileFacts};

pub use resolve::{resolve, KotlinIndex, Resolved, RootIndex};

/// Bumped whenever extraction changes what it reads out of a file. The index
/// cache is keyed by blob, so without this a fixed extractor would never
/// reach a file that did not change.
pub const EXTRACTOR_VERSION: &str = "5";

/// Extract one file's facts. A file that fails to parse cleanly still yields
/// whatever the grammar recovered — tree-sitter parses around errors — so a
/// half-written file never drops out of the map.
pub fn extract(lang: CodeLang, text: &str) -> FileFacts {
    let mut facts = match lang {
        CodeLang::TypeScript => ts::extract(text, false),
        CodeLang::Tsx => ts::extract(text, true),
        CodeLang::Rust => rust::extract(text),
        CodeLang::Kotlin => kotlin::extract(text),
    };
    facts.generated = says_generated(text);
    facts
}

/// Whether a file's header says a tool wrote it — the conventions
/// generators follow so people and linters leave the file alone.
fn says_generated(text: &str) -> bool {
    text.lines().take(5).any(|line| {
        let l = line.to_ascii_lowercase();
        l.contains("@generated")
            || l.contains("do not edit")
            || l.contains("code generated")
            || l.contains("auto-generated")
            || l.contains("autogenerated")
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_header_that_says_generated_marks_the_file() {
        let made = "// Code generated by metaphor. DO NOT EDIT.\nexport const x = 1;\n";
        assert!(extract(CodeLang::TypeScript, made).generated);
        let written = "export const x = 1;\n// later: do not edit this by hand? no\n";
        assert!(!extract(CodeLang::TypeScript, "export const x = 1;\n").generated);
        assert!(
            extract(CodeLang::TypeScript, written).generated,
            "within the first lines"
        );
    }
}
